version: '3.8'

services:
  ollama-cpu:
    env_file: .env
    image: ollama/ollama:latest
    container_name: ollama-cpu
    ports:
      - "${AI_PORT}:11434"
    volumes:
      - ollama-data:/root/.ollama
    deploy:
      restart_policy:
        condition: always
      resources:
          limits:
            memory: 4G
    tty: true
    networks:
      - ollama-docker

volumes:
  ollama-data:
    driver: local

networks:
  ollama-docker:
    external: false

