version: '3.8'

services:
  ollama-cpu:
    env_file: .env
    image: ollama/ollama:latest
    container_name: ollama-cpu
    ports:
      - "${AI_CPU_PORT}:11434"
    volumes:
      - ollama-data:/root/.ollama
    deploy:
      restart_policy:
        condition: always
    tty: true
    networks:
      - ollama-docker

  ollama-gpu:
    image: ollama/ollama:latest
    env_file: .env
    container_name: ollama-gpu
    ports:
      - "${AI_GPU_PORT}:11434"
    volumes:
      - ollama-data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
      restart_policy:
        condition: always
    tty: true
    networks:
      - ollama-docker

volumes:
  ollama-data:
    driver: local

networks:
  ollama-docker:
    external: false

