name: Golang Lint

on:
  push:
    branches: ["*"]
    types: [opened, synchronize, reopened]
  pull_request:
    branches: [ "*" ]
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read

jobs:
  golang-lint:
    runs-on: ubuntu-latest
    name: Golang Lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Golang setup
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Golang Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59
