name: Comment on PR Files

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  comment-files:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Run Go script
      run: go run .
      env:
        ACESS_TOKEN: ${{ secrets.ACESS_TOKEN }}
        REPOSITORY_OWNER: ${{ github.repository_owner }}
        REPOSITORY_NAME: ${{ github.event.pull_request.head.repo.name }}
        PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
