name: Comment on PR Files

on:
  pull_request:
    types: [opened]

jobs:
  comment-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Run Go script
      run: go run ./pkg/github/github.go
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
        GITHUB_REPOSITORY_NAME: ${{ github.event.pull_request.head.repo.name }}
        GITHUB_PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
