name: Comment on PR Files

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  comment-files:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Run Go script
      run: go run .
      env:
        ACTION_ACCESS_TOKEN: ${{ secrets.ACTION_ACCESS_TOKEN }}
        REPOSITORY_OWNER: ${{ github.repository_owner }}
        REPOSITORY_NAME: ${{ github.event.pull_request.head.repo.name }}
        PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
        AI_MODEL_NAME: "tinyllama"
        AI_PORT: 1111
        AI_PROMPT: "Provide a short explanation about the code below:"
        AI_TEMPERATURE: 0.3
